services:

  child1.api:
    image: ghcr.io/saifdevopz/child1-api:latest
    container_name: Starter.Child1.API 
    build:
      context: .
      dockerfile: src/api/Child1.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8056:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.child1-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.child1-api.entrypoints=https"
      - "traefik.http.routers.child1-api.rule=Host(`child1.webport.co.za`)"
      - "traefik.http.routers.child1-api.tls=true"
      - "traefik.http.routers.child1-api.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true


