services:

  blazor.server:
    image: ghcr.io/saifdevopz/blazor-server:latest
    container_name: Starter.BlazorServer
    build:
      context: .
      dockerfile: src/apps/blazor-server/BlazorServerTemplate/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8098:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blazor-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.blazor-api.entrypoints=https"
      - "traefik.http.routers.blazor-api.rule=Host(`blazorserver.webport.co.za`)"
      - "traefik.http.routers.blazor-api.tls=true"
      - "traefik.http.routers.blazor-api.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true



