apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi-container
        image: weatherapi-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
spec:
  selector:
    app: weatherapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080    
  type: NodePort    